"""
Execution manager.

Executes the steps generated by the planner.
"""

import os
import re
import socket
import time

from services.code_service import CodeService
from services.filesystem import FilesystemService
from services.live_data_service import LiveDataService
from services.python_runner import PythonRunnerService
from services.semantic_index import SemanticIndex
from services.system_service import SystemService
from services.web_service import WebService


# Lookups that return a figure rather than pages to read.
_LIVE_DATA_TOOLS = {"weather.current", "finance.quote", "finance.exchange"}


def _live_data_fallback_query(tool, args):
    """Search wording to try when a structured lookup can't answer."""

    if tool == "weather.current":
        location = args.get("location") or args.get("place") or args.get("city")
        return (f"current weather in {location}", "weather") if location else (None, None)

    if tool == "finance.quote":
        symbol = args.get("symbol") or args.get("ticker")
        return (f"{symbol} share price", "finance") if symbol else (None, None)

    if tool == "finance.exchange":
        base = args.get("base") or args.get("from")
        target = args.get("target") or args.get("to")
        if base and target:
            return (f"{base} to {target} exchange rate", "finance")
        return (None, None)

    return (None, None)


# Hosts used only to prove the network is reachable. Two of them, on
# different operators, so one being down doesn't read as "no internet".
_CONNECTIVITY_HOSTS = (("1.1.1.1", 53), ("8.8.8.8", 53))
_CONNECTIVITY_TIMEOUT = 1.5
_CONNECTIVITY_CACHE_SECONDS = 30

_connectivity_cache = {"checked_at": 0.0, "online": None}


def has_internet(force: bool = False) -> bool:
    """Whether the network is reachable, cached briefly.

    A raw socket to a DNS port rather than an HTTP request: it answers
    in milliseconds when the link is up and fails fast when it isn't,
    where a real request spends its full timeout finding out. The cache
    keeps a multi-query plan from re-checking before every search.
    """

    now = time.monotonic()

    if (
        not force
        and _connectivity_cache["online"] is not None
        and now - _connectivity_cache["checked_at"] < _CONNECTIVITY_CACHE_SECONDS
    ):
        return _connectivity_cache["online"]

    # Both hosts get a second pass before this reports offline. A live
    # weather query on a real browser session was told "I can't reach
    # the network right now" while the connection was actually fine -
    # every message before and after it worked - and both hosts answer
    # in under 50ms on a normal link. A laptop's Wi-Fi drops for well
    # under a second during roaming or a DHCP renewal, which is enough
    # to lose a single fast attempt but not two attempts a beat apart.
    # A real outage still fails both passes and reports offline, in
    # under a second longer than one pass would have taken.
    for attempt in range(2):

        online = False

        for host, port in _CONNECTIVITY_HOSTS:
            try:
                with socket.create_connection((host, port), _CONNECTIVITY_TIMEOUT):
                    online = True
                    break
            except OSError:
                continue

        if online:
            break

        if attempt == 0:
            time.sleep(0.5)

    _connectivity_cache["checked_at"] = now
    _connectivity_cache["online"] = online

    return online


class ExecutionManager:

    def __init__(self, model):
        self.python = PythonRunnerService()
        self.filesystem = FilesystemService()
        self.web = WebService()
        self.live = LiveDataService()
        self.system = SystemService()
        self.code = CodeService(model)

        # Shares the filesystem service so document text is extracted
        # one way only - the same code that reads a PDF for an answer
        # reads it for the index.
        self.semantic = SemanticIndex(self.filesystem)

        # Overwritten by the agent to match the chosen mode. The
        # default matches what every search used before modes could
        # change it, so an executor built on its own behaves as before.
        self.search_results = 4

    def _execute_semantic_search(self, query: str):
        """Search documents by meaning, indexing first if needed.

        The index is built on the first search rather than at startup.
        Reading every document on a machine takes minutes, and doing it
        before anyone has asked for it would make Athena appear to hang
        on launch - and would read files the user never intended to
        hand over.
        """

        if not query.strip():
            return {"success": False, "error": "What should I look for?"}

        result = self.semantic.search(query)

        if result.get("needs_index"):

            print("[SEMANTIC] no index yet -> building one")

            built = self.semantic.index()

            if not built.get("success"):
                return built

            print(f"[SEMANTIC] indexed {built['indexed']} document(s)")

            result = self.semantic.search(query)

        return result

    @staticmethod
    def _get_search_queries(args):
        """
        Return up to three unique web-search queries.

        Supports both:
            {"query": "main query"}

        and:
            {
                "query": "main query",
                "queries": ["variant one", "variant two"]
            }
        """

        queries = []

        primary_query = args.get("query")

        if isinstance(primary_query, str):
            queries.append(primary_query)

        variants = args.get("queries", [])

        if isinstance(variants, str):
            variants = [variants]

        if isinstance(variants, list):
            queries.extend(variants)

        cleaned_queries = []
        seen = set()

        for query in queries:
            if not isinstance(query, str):
                continue

            query = " ".join(query.split())

            if not query:
                continue

            key = query.casefold()

            if key in seen:
                continue

            seen.add(key)
            cleaned_queries.append(query)

            if len(cleaned_queries) == 3:
                break

        return cleaned_queries

    _DATE_PATTERNS = [
        # "10 August 2026" / "10 Aug 2026"
        r"\b\d{1,2}\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?,?\s+\d{4}\b",
        # "August 10, 2026" / "Aug 10 2026"
        r"\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+\d{1,2},?\s+\d{4}\b",
        # "August 2026"
        r"\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\.?\s+\d{4}\b",
        # 2026-08-10 / 10/08/2026 / 10-08-2026
        r"\b\d{4}[-/]\d{1,2}[-/]\d{1,2}\b",
        r"\b\d{1,2}[-/]\d{1,2}[-/]\d{4}\b",
        # bare year
        r"\b(?:19|20)\d{2}\b",
    ]

    @classmethod
    def _normalize_weather_query(cls, query):
        """Strip explicit dates out of weather queries.

        The planner is told to put today's date into time-sensitive
        queries, which is right for news or sports but backfires
        badly for weather: search engines read "London weather 10
        August 2026" as a request for an archive, and return monthly
        and historical summary pages instead of current conditions.
        Those pages genuinely do not contain today's weather, so no
        amount of downstream grounding can recover the answer.

        Enforced here rather than in the planner prompt because the
        prompt already asks for the opposite behaviour for other
        categories.
        """

        cleaned = query

        for pattern in cls._DATE_PATTERNS:
            cleaned = re.sub(pattern, " ", cleaned, flags=re.IGNORECASE)

        cleaned = " ".join(cleaned.split())

        if not cleaned:
            return query

        if not re.search(r"\b(today|now|current|currently|tonight)\b", cleaned, re.IGNORECASE):
            cleaned = f"{cleaned} today"

        return cleaned

    @staticmethod
    def _deduplicate_pages(pages):
        """
        Remove duplicate web pages while preserving their original order.
        """

        unique_pages = []
        seen = set()

        for page in pages:
            if not isinstance(page, dict):
                continue

            url = str(page.get("url", "")).strip()
            title = str(page.get("title", "")).strip()
            snippet = str(page.get("snippet", "")).strip()

            if url:
                key = ("url", url.casefold())
            else:
                key = (
                    "content",
                    title.casefold(),
                    snippet.casefold(),
                )

            if key in seen:
                continue

            seen.add(key)
            unique_pages.append(page)

        return unique_pages

    def _find_by_bare_name(self, tool, path):
        """Search for a file when given its name instead of its path.

        The planner sometimes answers "is there a file named hostel
        fees" with filesystem.read on the path "hostel fees", which is
        a name and not a path, so the read failed with "File does not
        exist." for a file that was sitting on the Desktop. Prompt
        wording moved this between read, info and search across
        sessions without settling it, so a name that cannot be a path
        is turned into a search here instead.

        Returns a search result to use in place of the original step,
        or None to carry on with the step as planned.
        """

        if not path or not isinstance(path, str):
            return None

        # A real path has a separator or a drive, or simply exists.
        if os.path.sep in path or "/" in path or os.path.splitdrive(path)[0]:
            return None

        if os.path.exists(path):
            return None

        print(f"[FALLBACK] '{path}' is a name, not a path -> filesystem.search")

        result = self.filesystem.search(path)

        if isinstance(result, dict):
            result["fell_back_from"] = tool
            result["fell_back_to"] = "filesystem.search"

        return result

    def _run_live_lookup(self, tool, args):
        """Dispatch to the structured source for this tool."""

        if tool == "weather.current":
            return self.live.weather(
                args.get("location") or args.get("place") or args.get("city", "")
            )

        if tool == "finance.quote":
            return self.live.quote(
                args.get("symbol") or args.get("ticker", "")
            )

        if tool == "finance.exchange":
            return self.live.exchange(
                args.get("base") or args.get("from", ""),
                args.get("target") or args.get("to", ""),
                args.get("amount", 1),
            )

        return {"success": False, "error": f"Unknown lookup: {tool}"}

    def _execute_live_data(self, tool, args):
        """Run a structured lookup, falling back to a search if it can't
        answer.

        The structured sources are narrower than the web: a geocoder
        knows the towns in its gazetteer, and a ticker lookup knows
        listed symbols. Asked for somewhere it hadn't heard of, the
        lookup failed and the whole request stopped there - where a
        plain search would very likely have found it. Trying the search
        costs the time of the request that already failed, and only on
        the requests that failed.
        """

        if not has_internet():
            print(f"[NETWORK] no connectivity -> skipping {tool}")
            return {
                "success": False,
                "offline": True,
                "error": (
                    "That needs the internet, and I can't reach the network "
                    "right now. Files, code and anything already on this "
                    "machine still work."
                ),
            }

        result = self._run_live_lookup(tool, args)

        if result.get("success"):
            return result

        # A clarification is a valid, user-facing outcome. Falling back
        # to generic search would pick an arbitrary point inside a
        # country and present it as that country's weather.
        if result.get("needs_clarification"):
            return result

        query, category = _live_data_fallback_query(tool, args)

        if not query:
            return result

        print(f"[FALLBACK] {tool} could not answer -> web.search")

        search = self._execute_web_search({"query": query, "category": category})

        if search.get("success"):
            # Flagged so the step can be re-labelled as the search it
            # actually became. The evidence is now web pages, and the
            # prompt and grounding rules for those are not the ones for
            # a structured lookup.
            search["fell_back_from"] = tool
            search["fell_back_to"] = "web.search"
            return search

        # The structured error names the actual problem ("I couldn't
        # find a place called ..."), which is more use than a generic
        # search failure.
        return result

    def _execute_web_search(self, args):
        queries = self._get_search_queries(args)

        if not queries:
            return {
                "success": False,
                "error": "A web search query was not provided.",
            }

        # Checked before searching rather than discovered through
        # failures. Offline, each query used to burn its own timeout and
        # then report that the searches "failed", which reads as a
        # broken assistant rather than a missing network. Everything
        # that doesn't need the network - files, code, the clock - is
        # unaffected, because only this branch is gated.
        if not has_internet():
            print("[NETWORK] no connectivity -> skipping web search")
            return {
                "success": False,
                "offline": True,
                "error": (
                    "That needs the internet, and I can't reach the network "
                    "right now. Files, code and anything already on this "
                    "machine still work."
                ),
            }

        category = args.get("category", "general")

        if category not in {"sports", "finance", "weather", "general"}:
            category = "general"

        if category == "weather":

            normalized = []

            for query in queries:

                cleaned = self._normalize_weather_query(query)

                if cleaned.casefold() not in {q.casefold() for q in normalized}:
                    normalized.append(cleaned)

            if normalized != queries:
                print(f"[WEB SEARCH] weather queries normalized: {queries} -> {normalized}")

            queries = normalized

        all_pages = []
        errors = []
        successful_searches = 0

        for query in queries:
            try:
                result = self.web.search(
                    query,
                    category=category,
                    # Set by the mode. More results means more to read
                    # and more to check, which is why only the slowest
                    # mode raises it.
                    max_results=self.search_results,
                )
            except Exception as error:
                errors.append(f"{query}: {error}")
                continue

            if not isinstance(result, dict):
                errors.append(
                    f"{query}: The web service returned an invalid result."
                )
                continue

            if not result.get("success", True):
                errors.append(
                    f"{query}: {result.get('error', 'Web search failed.')}"
                )
                continue

            successful_searches += 1

            data = result.get("data", [])

            if isinstance(data, list):
                all_pages.extend(data)

        if successful_searches == 0:
            return {
                "success": False,
                "error": (
                    "All web searches failed. "
                    + " | ".join(errors)
                ),
            }

        result = {
            "success": True,
            "data": self._deduplicate_pages(all_pages),
            "queries": queries,
            "category": category,
        }

        if errors:
            result["warnings"] = errors

        return result

    def _execute_step(self, tool, args):
        if tool == "chat":
            return {
                "success": True,
                "type": "chat",
                "data": None,
            }

        if tool == "system.datetime":
            return self.system.datetime_now(
                args.get("timezone")
            )

        if tool == "filesystem.list":
            return self.filesystem.list(
                args.get("path", ".")
            )

        if tool in {"filesystem.read", "filesystem.info", "filesystem.exists"}:

            path = args.get("path", "")
            found = self._find_by_bare_name(tool, path)

            if found is not None:
                return found

            if tool == "filesystem.read":
                return self.filesystem.read(path)

            if tool == "filesystem.info":
                return self.filesystem.info(path)

            return self.filesystem.exists(path)

        if tool == "filesystem.search":
            return self.filesystem.search(
                args.get("name", "")
            )

        if tool == "filesystem.semantic_search":
            # "name" as well as "query": the planner has confused the
            # two argument names for sibling capabilities before, and a
            # silent empty search is a miserable way to find out.
            return self._execute_semantic_search(
                args.get("query") or args.get("name") or ""
            )

        if tool == "web.search":
            return self._execute_web_search(args)

        if tool in _LIVE_DATA_TOOLS:
            return self._execute_live_data(tool, args)

        if tool == "python.run":

            path = args.get("path") or args.get("file")

            if path:
                return self.python.run(path)

            snippet = args.get("code") or args.get("snippet")

            if snippet:
                return self.code.run_snippet(snippet)

            return {
                "success": False,
                "error": "No script path was provided to run.",
            }

        if tool == "code.generate":
            return self.code.generate(
                args.get("spec", ""),
                args.get("path", ""),
                args.get("overwrite", False),
            )

        if tool == "code.run":

            # The two run steps get mixed up: code.run is sometimes
            # given the path of a script just generated, and python.run
            # is sometimes given a snippet. Both were then handed an
            # empty argument and failed instantly with nothing to show,
            # which surfaced as "I couldn't find that". Whichever
            # argument arrived is honoured.
            snippet = args.get("code") or args.get("snippet")

            if snippet:
                return self.code.run_snippet(snippet)

            path = args.get("path") or args.get("file")

            if path:
                return self.python.run(path)

            return {
                "success": False,
                "error": "No code or script path was provided to run.",
            }

        return {
            "success": False,
            "error": f"Unknown tool: {tool}",
        }

    def execute(self, plan):
        results = []

        if not isinstance(plan, dict):
            return [
                {
                    "success": False,
                    "error": "The execution plan must be a dictionary.",
                }
            ]

        steps = plan.get("steps", [])

        if not isinstance(steps, list):
            return [
                {
                    "success": False,
                    "error": "The plan's steps must be a list.",
                }
            ]

        for step in steps:
            if not isinstance(step, dict):
                results.append(
                    {
                        "success": False,
                        "error": "Invalid plan step.",
                    }
                )
                continue

            tool = step.get("type")
            args = step.get("args", {})

            if not isinstance(args, dict):
                args = {}

            try:
                result = self._execute_step(tool, args)
            except Exception as error:
                result = {
                    "success": False,
                    "error": f"{tool or 'Unknown tool'} failed: {error}",
                }

            # A lookup that fell back returned web pages, not fields.
            # Everything downstream reads the step type to decide how to
            # format and grade the evidence, so the step is relabelled
            # to what actually ran - otherwise the prompt builder would
            # try to read a list of pages as a weather reading.
            if isinstance(result, dict) and result.get("fell_back_to"):
                step["type"] = result["fell_back_to"]

            results.append(result)

        return results
